/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.Vista;

import biblioteca.Controlador.Controlador;
import biblioteca.Modelo.Libro;
import biblioteca.Modelo.ConexionBD;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class SolicitudLibro extends javax.swing.JFrame {

    private Controlador capLibro;

    /**
     * @return the capLibro
     */
    public Controlador getCapLibro() {
        return capLibro;
    }

    /**
     * @param capLibro the capLibro to set
     */
    public void setCapLibro(Controlador capLibro) {
        this.capLibro = capLibro;
    }

    /**
     * Creates new form solicitudLibro
     */
    public SolicitudLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombreLibro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombreLibro = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablibros = new javax.swing.JTable();
        btnregistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnombreLibro.setText("Nombre Libro");

        jLabel2.setText("SOLICITUD DE LIBRO");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jtablibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Biblioteca", "Id_Libro", "Id_Satelite", "Titulo", "Edicion", "Disponible"
            }
        ));
        jtablibros.setToolTipText("");
        jScrollPane1.setViewportView(jtablibros);

        btnregistrar.setText("REGISTRAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblnombreLibro)
                        .addGap(50, 50, 50)
                        .addComponent(txtnombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnregistrar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombreLibro)
                    .addComponent(txtnombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnregistrar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        ConexionBD vc = new ConexionBD();
        vc.setConexionOracle("jdbc:oracle:thin:@172.17.1.25:1521:INGROUP", "USERSETA", "D4T4C3NT3R");
        setCapLibro(new Controlador(vc));
        String nombreLibro = txtnombreLibro.getText();

        List<Libro> list = getCapLibro().listaLibros(nombreLibro);
        if (list.isEmpty()) {
            System.out.println("No se encontro");
        } else {
            for (int i = 0; i < list.size(); i++) {

                System.out.println(list.get(i).getTitulo());

            }

            String[][] celdas = new String[list.size()][6];
            DefaultTableModel tmTablaLibros;

            for (int i = 0; i < celdas.length; i++) {
                celdas[i][3] = list.get(i).getTitulo();

            }

            tmTablaLibros = new DefaultTableModel(celdas, new String[]{
                "Id_Biblioteca", "Id_Libro", "Id_Satelite", "Titulo", "Edicion", "Disponible"
            });
            
            jtablibros.setModel(tmTablaLibros);
//            tmTablaLibros.fireTableDataChanged();
//            jtablibros.repaint();

        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablibros;
    private javax.swing.JLabel lblnombreLibro;
    private javax.swing.JTextField txtnombreLibro;
    // End of variables declaration//GEN-END:variables
}
